services:
  papirus-ai-landing:
    build:
      context: .
    container_name: papirus-ai-landing
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
